### ISSUE TITLE
Startup failure

### ISSUE THREAD

**Issue by Xavyrr** [NatTupper/Discline#1]
Installed the dev branch of mistletoe and got this error on startup:

```
Starting...

/home/xavyrr/Discline/client/client.py:45: RuntimeWarning: coroutine 'init_channel_messageEdit' was never awaited
  init_channel_messageEdit(channel)
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "Discline.py", line 61, in on_ready
    gc.client.current_channel = settings["default_channel"].lower()
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 302, in __setattr__
    object.__setattr__(self, name, value)
  File "/home/xavyrr/Discline/client/client.py", line 58, in current_channel
    self._prompt = channel.name
AttributeError: 'str' object has no attribute 'name'
^CTraceback (most recent call last):
  File "Discline.py", line 225, in <module>
    if __name__ == "__main__": main()
  File "Discline.py", line 213, in main
    curses.nocbreak()
_curses.error: must call initscr() first
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2f2ec3d198>
```

**Comment by NatTupper** [comment]
Can you reset your config to default and try that? If you do that, you'll also need to join the Discline discord server. I do recommend this anyhow.

**Comment by Xavyrr** [comment]
Doesn't seem to have fixed it, I removed the config with
`rm ~/.config/Discline/config`
and then cloned the skeleton config with
`rm ~/.config/Discline/config`
The error is identical.

**Comment by NatTupper** [comment]
How long ago did you clone the repository?

**Comment by Xavyrr** [comment]
I re cloned it last night before reporting back. I have also uninstalled all the python dependencies with `pip3 uninstall <dependency package names>` and have reinstalled them with the `no-cache-dir` argument to make sure the downloads were fresh. I should note that the client does work with the original master branch.  Looking at my error it seems to me that it's potentially related to discord.py, but I can't say for sure.

**Comment by NatTupper** [comment]
The original master branch being Mitch's repo? Hmm... the error on line 58 seems to have occurred due to the `if type(channel) is str:` check being skipped somehow. I'm not sure why. What version of discord.py do you have?

**Comment by Xavyrr** [comment]
It should be the latest available from using pip3, so 0.16.12 I think.

**Comment by NatTupper** [comment]
That is the latest version. Could you try an alt account? If the alt account works, then it's not your system that's the problem, it's discline.

**Comment by Xavyrr** [comment]
I just tried a freshly made account with a single test server, I still get the same error.

**Comment by NatTupper** [comment]
Okay. I'm able to replicate it with a default config. Looking into fixing it.

**Comment by NatTupper** [comment]
Okay. So it looks like the default config defines `default_server` as `discline`. Changing `discline` to `Discline` fixes the bug for me.

**Comment by Xavyrr** [comment]
Going into my config DID fix it! Thanks for the help.
