### ISSUE TITLE
Formatting inconsistency?

### ISSUE THREAD

**Issue by Xavyrr** [NatTupper/Discline#2]
Names with non-alphanumeric characters don't display a colon after their names.
Messages are formatted something like,
`NAME+": "+MESSAGE`
However if the name has say, Japanese characters in it, the semicolon is dropped.
![screenshot from 2018-05-17 19-37-57](https://user-images.githubusercontent.com/10913345/40208844-d141a48c-5a09-11e8-87a2-86a6f1c80ff5.png)
This issue does not occur in older versions like this:
![screenshot from 2018-05-17 19-40-40](https://user-images.githubusercontent.com/10913345/40208900-31d2e892-5a0a-11e8-8818-511b5a187e53.png)

**Comment by NatTupper** [comment]
I am aware of this bug. It's probably something due to the way curses renders multibyte characters.
